// @generated by protoc-gen-es v0.1.1 with parameter "target=ts+js"
// @generated from file web/v1/index.proto (package web.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3, Timestamp} from "@bufbuild/protobuf";
import {UserProfile} from "./user_pb.js";

/**
 * @generated from message web.v1.CreateIndexRequest
 */
export const CreateIndexRequest = proto3.makeMessageType(
  "web.v1.CreateIndexRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "public", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message web.v1.Index
 */
export const Index = proto3.makeMessageType(
  "web.v1.Index",
  () => [
    { no: 1, name: "public_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "created_at", kind: "message", T: Timestamp },
    { no: 4, name: "public", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message web.v1.CreateIndexResponse
 */
export const CreateIndexResponse = proto3.makeMessageType(
  "web.v1.CreateIndexResponse",
  () => [
    { no: 1, name: "index", kind: "message", T: Index },
  ],
);

/**
 * @generated from message web.v1.ListIndexesRequest
 */
export const ListIndexesRequest = proto3.makeMessageType(
  "web.v1.ListIndexesRequest",
  () => [
    { no: 1, name: "owned_by_user", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message web.v1.PossiblySubscribedIndex
 */
export const PossiblySubscribedIndex = proto3.makeMessageType(
  "web.v1.PossiblySubscribedIndex",
  () => [
    { no: 1, name: "index", kind: "message", T: Index },
    { no: 2, name: "subscribed_at", kind: "message", T: Timestamp, opt: true },
  ],
);

/**
 * @generated from message web.v1.ListIndexesResponse
 */
export const ListIndexesResponse = proto3.makeMessageType(
  "web.v1.ListIndexesResponse",
  () => [
    { no: 1, name: "indexes", kind: "message", T: PossiblySubscribedIndex, repeated: true },
  ],
);

/**
 * @generated from message web.v1.GetIndexRequest
 */
export const GetIndexRequest = proto3.makeMessageType(
  "web.v1.GetIndexRequest",
  () => [
    { no: 1, name: "public_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "include_owner", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 3, name: "include_subscribers_count", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 4, name: "include_subscribed_at", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ],
);

/**
 * @generated from message web.v1.GetIndexResponse
 */
export const GetIndexResponse = proto3.makeMessageType(
  "web.v1.GetIndexResponse",
  () => [
    { no: 1, name: "index", kind: "message", T: Index },
    { no: 2, name: "owner", kind: "message", T: UserProfile, opt: true },
    { no: 3, name: "subscribers_count", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 4, name: "subscribed_at", kind: "message", T: Timestamp, opt: true },
  ],
);

/**
 * @generated from message web.v1.UpdateIndexRequest
 */
export const UpdateIndexRequest = proto3.makeMessageType(
  "web.v1.UpdateIndexRequest",
  () => [
    { no: 1, name: "public_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "public", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ],
);

/**
 * @generated from message web.v1.UpdateIndexResponse
 */
export const UpdateIndexResponse = proto3.makeMessageType(
  "web.v1.UpdateIndexResponse",
  () => [
    { no: 1, name: "index", kind: "message", T: Index },
  ],
);

/**
 * @generated from message web.v1.DeleteIndexRequest
 */
export const DeleteIndexRequest = proto3.makeMessageType(
  "web.v1.DeleteIndexRequest",
  () => [
    { no: 1, name: "public_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message web.v1.DeleteIndexResponse
 */
export const DeleteIndexResponse = proto3.makeMessageType(
  "web.v1.DeleteIndexResponse",
  [],
);

/**
 * @generated from message web.v1.SubscriptionsRequest
 */
export const SubscriptionsRequest = proto3.makeMessageType(
  "web.v1.SubscriptionsRequest",
  [],
);

/**
 * @generated from message web.v1.SubscriptionsResponse
 */
export const SubscriptionsResponse = proto3.makeMessageType(
  "web.v1.SubscriptionsResponse",
  () => [
    { no: 1, name: "indexes", kind: "message", T: PossiblySubscribedIndex, repeated: true },
  ],
);

/**
 * @generated from message web.v1.SubscribeRequest
 */
export const SubscribeRequest = proto3.makeMessageType(
  "web.v1.SubscribeRequest",
  () => [
    { no: 1, name: "public_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message web.v1.SubscribeResponse
 */
export const SubscribeResponse = proto3.makeMessageType(
  "web.v1.SubscribeResponse",
  () => [
    { no: 1, name: "index", kind: "message", T: PossiblySubscribedIndex },
  ],
);

/**
 * @generated from message web.v1.UnsubscribeRequest
 */
export const UnsubscribeRequest = proto3.makeMessageType(
  "web.v1.UnsubscribeRequest",
  () => [
    { no: 1, name: "public_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message web.v1.UnsubscribeResponse
 */
export const UnsubscribeResponse = proto3.makeMessageType(
  "web.v1.UnsubscribeResponse",
  () => [
    { no: 1, name: "index", kind: "message", T: PossiblySubscribedIndex },
  ],
);

