// @generated by protoc-gen-es v0.1.1 with parameter "target=ts+js"
// @generated from file web/v1/key.proto (package web.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3, Timestamp} from "@bufbuild/protobuf";

/**
 * @generated from message web.v1.APIKey
 */
export const APIKey = proto3.makeMessageType(
  "web.v1.APIKey",
  () => [
    { no: 1, name: "created_at", kind: "message", T: Timestamp },
    { no: 2, name: "last_used", kind: "message", T: Timestamp, opt: true },
    { no: 3, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message web.v1.CreateKeyRequest
 */
export const CreateKeyRequest = proto3.makeMessageType(
  "web.v1.CreateKeyRequest",
  [],
);

/**
 * @generated from message web.v1.CreateKeyResponse
 */
export const CreateKeyResponse = proto3.makeMessageType(
  "web.v1.CreateKeyResponse",
  () => [
    { no: 1, name: "key", kind: "message", T: APIKey },
  ],
);

/**
 * @generated from message web.v1.ListKeysRequest
 */
export const ListKeysRequest = proto3.makeMessageType(
  "web.v1.ListKeysRequest",
  [],
);

/**
 * @generated from message web.v1.ListKeysResponse
 */
export const ListKeysResponse = proto3.makeMessageType(
  "web.v1.ListKeysResponse",
  () => [
    { no: 1, name: "keys", kind: "message", T: APIKey, repeated: true },
  ],
);

/**
 * @generated from message web.v1.DeleteKeyRequest
 */
export const DeleteKeyRequest = proto3.makeMessageType(
  "web.v1.DeleteKeyRequest",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message web.v1.DeleteKeyResponse
 */
export const DeleteKeyResponse = proto3.makeMessageType(
  "web.v1.DeleteKeyResponse",
  [],
);

