// @generated by protoc-gen-connect-web v0.7.0 with parameter "target=ts"
// @generated from file operand/v1/operand.proto (package operand.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ConverseRequest, ConverseResponse, SearchRequest, SearchResponse } from "./operand_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * OperandService provides a number of core operations on top of files.
 *
 * @generated from service operand.v1.OperandService
 */
export const OperandService = {
  typeName: "operand.v1.OperandService",
  methods: {
    /**
     * Search returns a list of snippets that match the given query, along with
     * all the relevant files that contain the snippets.
     *
     * @generated from rpc operand.v1.OperandService.Search
     */
    search: {
      name: "Search",
      I: SearchRequest,
      O: SearchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Converse exposes a chatbot with knowledge backed by the content
     * of uploaded files. Each conversation is associated with a unique
     * identifier, which can be passed in again to continue the conversation.
     *
     * @generated from rpc operand.v1.OperandService.Converse
     */
    converse: {
      name: "Converse",
      I: ConverseRequest,
      O: ConverseResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

