name: Npm Publish
on:
  release:
    types: [published]
jobs:
  build:
    name: 'Build and publish to NPM'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install deps
        uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish --access=public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
